[package]
name = "cargo-all-features"
version = "1.6.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2021"
description = "A Cargo subcommand to build and test all feature flag combinations"
repository = "https://github.com/frewsxcv/cargo-all-features"
license = "MIT/Apache-2.0"
readme = "./README.md"

[dependencies]
json = "0.12"
itertools = "0.10"
termcolor = "1"
clap = "=3.0.0-beta.5"
strum_macros = "0.23.1"
strum = "0.23.0"
